# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('asknbid_id', models.CharField(max_length=30, null=True, unique=True)),
                ('account_status', models.CharField(choices=[('Submitted', 'Submitted'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], max_length=20)),
                ('accont_created_on', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc_code', models.CharField(default='', max_length=10)),
                ('time', models.TimeField(auto_now_add=True)),
                ('source', models.CharField(default='', max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('activity', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('valid', models.BooleanField(default=False)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('full_name', models.CharField(max_length=100)),
                ('pan_number', models.CharField(default='', max_length=10)),
                ('adhaar_no', models.CharField(default='', max_length=12)),
                ('gross_annual_income', models.CharField(default='', max_length=12)),
                ('residential_status', models.CharField(default='', max_length=200)),
                ('street_address', models.CharField(default='', max_length=30)),
                ('city', models.CharField(default='', max_length=30)),
                ('state', models.CharField(default='', max_length=30)),
                ('country', models.CharField(default='', max_length=30)),
                ('pin_code', models.CharField(default='', max_length=10)),
                ('kyc_status', models.CharField(choices=[('Submitted', 'Submitted'), ('Pending', 'Pending'), ('Verified', 'Verified')], max_length=30)),
                ('valid', models.BooleanField(default=False)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='KYC_Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_card', models.ImageField(upload_to='media/upload/pancard')),
                ('adhaar_card', models.ImageField(upload_to='media/upload/adhaarcard')),
                ('adhaar_back', models.ImageField(upload_to='media/upload/adhaarback')),
                ('photograph', models.ImageField(upload_to='media/upload/photograph')),
                ('valid', models.BooleanField(default=False)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
    ]
