# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-26 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
